### ISSUE TITLE
Cannot Build .DLL file

### ISSUE THREAD

**Issue by F-I-E-N-D** [nalexandru/ToneMapping#1]
Hello, hope all is well. For some unknown reason, I am unable to build the .dll file from the provided project. Is it possible you could just upload the .dll file itself or at leat help me troubleshoot this? Thanks in advance.

Error	1	error MSB6006: "cmd.exe" exited with code 9009.	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets	151	6	ToneMapping

I am using VS2010 like you instructed.

**Comment by nalexandru** [comment]
Hello, sorry for the delay in responding.

The .dll is uploaded on the releases page, a version for 64-bit Windows and one for 64-bit Mac.

The build failed because i have the Daz SDK installed in a non-standard path and i forgot to correct the project file before commiting. I have fixed the issue, the build should work with the SDK installed in the default DIM library location (C:\Users\Public\Documents\My DAZ 3D Library).

**Comment by F-I-E-N-D** [comment]
It works, thank you so much for getting back to me!
